name: Create QOTD Image

on:
  workflow_dispatch:
    inputs:
      quote:
        description: 'Quote?'
        required: true

jobs:
  build:
    name: Create QOTD Image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v4
    - name: Create Image
      run: |
        export GITHUB_USER=kingthorin
        QOTD=qotd_$(cat /proc/sys/kernel/random/uuid).png
        rm *.png
        git config --global user.email "kingthorin@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git remote set-url origin https://$GITHUB_USER:${{ secrets.KINGTHORIN_QOTD }}@github.com/$GITHUB_USER/$GITHUB_USER
        sudo apt install imagemagick
        convert -background white -fill black -pointsize 14 -font DejaVu-Sans-Mono label:${{ github.event.inputs.quote }} -bordercolor white -border 24 $QOTD
        ls -lha *.png
        echo "![](https://raw.githubusercontent.com/kingthorin/kingthorin/main/$QOTD)" >> $GITHUB_STEP_SUMMARY
        sed -i "/id=\"qotd_dark_img\"/ s#qotd_[^\"]*\.png#${QOTD}#" README.md
        sed -i "/id=\"qotd_light_img\"/ s#qotd_[^\"]*\.png#${QOTD}#" README.md
        git add $QOTD
        git commit -m "Update QOTD" --signoff
        git push
