name: Create QOTD Image

on:
  workflow_dispatch:
    inputs:
      quote:
        description: 'Quote?'
        required: true

jobs:
  build:
    name: Create QOTD Image
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Create Image
      run: |
        export GITHUB_USER=kingthorin
        git config --global user.email "kingthorin@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git remote set-url origin https://$GITHUB_USER:${{ secrets.KINGTHORIN_QOTD }}@github.com/$GITHUB_USER/$GITHUB_USER
        convert -background white -fill black -pointsize 14 -font FreeMono label:${{ github.event.inputs.quote }} -bordercolor white -border 24 qotd.png
        git add qotd.png
        git commit -m "Update QOTD" --signoff
        git push
