name: Create QOTD Image

on:
  workflow_dispatch:
    inputs:
      quote:
        description: 'Quote?'
        required: true

jobs:
  build:
    name: Create QOTD Image
    runs-on: ubuntu-latest
    permissions:
      contents: write # Checkout and push QOTD image
    steps:
    - name: Setup Action
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Create Image
      env:
        GITHUB_EVENT_INPUTS_QUOTE: ${{ github.event.inputs.quote }}
        GH_TOKEN: ${{ github.token }}
      run: |
        export GITHUB_USER=kingthorin
        QOTD=qotd_$(cat /proc/sys/kernel/random/uuid).png
        rm *.png
        git config --global user.email "kingthorin@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        sudo apt install imagemagick
        convert -background white -fill black -pointsize 14 -font DejaVu-Sans-Mono label:${GITHUB_EVENT_INPUTS_QUOTE} -bordercolor white -border 24 $QOTD
        ls -lha *.png
        echo "![](https://raw.githubusercontent.com/kingthorin/kingthorin/main/$QOTD)" >> $GITHUB_STEP_SUMMARY
        sed -i "/id=\"qotd_dark_img\"/ s#qotd_[^\"]*\.png#${QOTD}#" README.md
        sed -i "/id=\"qotd_light_img\"/ s#qotd_[^\"]*\.png#${QOTD}#" README.md
        git add .
        git commit -m "Update QOTD" --signoff
        git push
