name: Update Stats Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Update Stats Image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v4
    - name: Update Image
      run: |
        export GITHUB_USER=kingthorin
        git config --global user.email "kingthorin@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git remote set-url origin https://$GITHUB_USER:${{ secrets.KINGTHORIN_QOTD }}@github.com/$GITHUB_USER/$GITHUB_USER
        # curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=kingthorin&show_icons=true&include_all_commits=true"
        curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=kingthorin&show_icons=true&include_all_commits=true&theme=dark"
        ls -lha *.svg
        echo "![](https://raw.githubusercontent.com/kingthorin/kingthorin/main/stats.svg)" >> $GITHUB_STEP_SUMMARY
        git add stats.svg
        git commit -m "Update Stats" --signoff
        git push
