name: Create Team Status Update

on:
  workflow_dispatch:
  schedule:
    - cron: '59 6 * * MON'

jobs:
  build:
    name: Team Status Update
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Setup Action
      uses: actions/checkout@v4
    - name: Create Update
      run: |
        first=$(date -d "last Tuesday" +%Y-%m-%d)
        last=$(date -d "next Tuesday" +%Y-%m-%d)

        # Special case: if today is Tuesday, override "last" to today
        if [ "$(date +%u)" -eq 2 ]; then
            last=$(date +%Y-%m-%d)
        fi
        echo $first
        echo $last

        file=index.html

        echo "" > $file

        commits_team() {
            echo $1 >> $file
            echo "<ul>" >> $file
            gh search prs --owner zaproxy --owner zapbot --author $2 --created $first..$last --json number,title,url -L 100 --jq '.[]|("<li><a href=\"" + .url + "\">#" + (.number|tostring) + "</a> " + .title)' >> $file
            echo "</ul>" >> $file
        }

        commits_team "Simon" "psiinon"
        commits_team "Ricardo" "thc202"
        commits_team "Rick" "kingthorin"

        echo "Contributors" >> $file
        echo "<ul>" >> $file

        echo "</ul>" >> $file

        cat $file >>  >> $GITHUB_STEP_SUMMARY
