name: Web Check

on:
  schedule:
  # Run every 0th minute for every third hour for hours 0-21
  - cron: "0 0-21/3 * * *"
  # Run every 30th minute for every third hour for hours 1-22 
  - cron: "30 1-22/3 * * *"
  workflow_dispatch:

jobs:
  web_check:
    name: Web Check
    runs-on: ubuntu-latest
    steps:
    - name: Take Screenshots
      run: |
        google-chrome --headless --disable-gpu --disable-software-rasterizer --screenshot=chrome_one.jpg \
          --window-size=1280,1600 --run-all-compositor-stages-before-draw --virtual-time-budget=10000 https://github.com/kingthorin &&
        ls -lha *.jpg
    - name: Attach Screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./*.jpg
