name: Web Check

on:
  workflow_dispatch:

jobs:
  web_check:
    name: Web Check
    runs-on: ubuntu-latest
    steps:
    - name: Take Screenshot One
      run: |
        curl https://github.com/kingthorin
        curl --http2 https://github.com/kingthorin
        google-chrome --headless --disable-gpu --disable-software-rasterizer --screenshot=chrome_one.jpg \
          --window-size=1280,1600 --run-all-compositor-stages-before-draw --virtual-time-budget=10000 https://github.com/kingthorin &&
        ls -lha *.jpg
    - name: Attach Screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./*.jpg
