name: Web Check

on:
  schedule:
  # Run every 0th minute for every third hour for hours 0-21
  - cron: "0 0-21/3 * * *"
  # Run every 30th minute for every third hour for hours 1-22 
  - cron: "30 1-22/3 * * *"
  workflow_dispatch:

jobs:
  web_check:
    name: Web Check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install dependencies
      run: npm install -g pageres-cli
    - name: Take Screenshot
      run: |
        wget -O- "https://github-readme-stats.kingthorin.vercel.app/api?username=kingthorin&show_icons=true&include_all_commits=true"
        sleep 15
        curl -s -f "https://github-readme-stats.kingthorin.vercel.app/api?username=kingthorin&show_icons=true&include_all_commits=true"
        pageres https://github.com/kingthorin/kingthorin/tree/master/.github/workflows 1024x768 --delay=5 --format=jpg --filename=screenshot && echo `ls -lh`
    - name: Attach Screenshot
      uses: actions/upload-artifact@v1
      with:
        name: screenshot
        path: screenshot.jpg
